CREATE UNIQUE INDEX Branch_index ON Branch (BranchID);
CREATE UNIQUE INDEX Customer_index ON Customer (Email_ID);
CREATE INDEX Customer_Phone_index ON Customer_Phone (CustomerID);
CREATE UNIQUE INDEX Employee_index ON Employee (EmployeeID);
CREATE INDEX Employee_Phone_index ON Employee_Phone (EmployeeID);
CREATE UNIQUE INDEX Manager_Employee_index ON Manager (EmployeeID);
CREATE UNIQUE INDEX Manager_Branch_index ON Manager (BranchID);
CREATE UNIQUE INDEX Supplier_index ON Supplier (SupplierID);
CREATE INDEX Supplier_Phone_index ON Supplier_Phone (SupplierID);
CREATE UNIQUE INDEX Product_index ON Product (ProductID);
CREATE INDEX Stock_Branch_index ON Stock (BranchID);
CREATE INDEX Stock_Barcode_index ON Stock (Barcode);
CREATE UNIQUE INDEX Coupon_index ON Coupon (CouponCode);
CREATE UNIQUE INDEX Account_index ON Account (LoginID);
CREATE INDEX Payment_Options_index ON Payment_Options (LoginID);
CREATE INDEX QnA_Product_index ON QnA (ProductID);
CREATE INDEX Answer_Question_index ON Answer (QuestionID);
CREATE UNIQUE INDEX DeliveryService_index ON DeliveryService (ServiceID);
CREATE INDEX DeliveryService_Phone_index ON DeliveryService_Phone (ServiceID);
CREATE INDEX Deliver_Service_index ON Deliver (ServiceID);
CREATE INDEX Deliver_Order_index ON Deliver (OrderID);
CREATE INDEX Review_Product_index ON Review (ProductID);
CREATE INDEX OnlineReturn_Order_index ON OnlineReturn (OrderID);
CREATE INDEX OnlineReturn_Service_index ON OnlineReturn (ServiceID);
CREATE INDEX Purchase_List_index ON Purchase_List (PurchaseID);
CREATE INDEX Cart_Login_index ON Cart (LoginID);
CREATE INDEX Wishlist_Login_index ON Wishlist (LoginID);